### ISSUE TITLE
二级路由刷新页面提示没有build.js

### ISSUE THREAD

**Issue by sunday-star** [ElementUI/element-starter#12]
正常的页面跳转是可以的，但是二级路由页面刷新就会报错，比如路由写成{path: '/home/:id', component: home}，这样的页面，就会出错，用了官方生成的界面，不会出现这样的问题，但是很喜欢element-starter的简洁配置，期望能解决我的疑惑，谢谢了

**Comment by yuanyuanshen** [comment]
<el-menu-item index="3" route="{path: '/home/:id'}">导航的路由跳转是这样么？

**Comment by yuanyuanshen** [comment]
<el-menu-item index="3" route="{path: '/home/:id'}">

**Comment by yuanyuanshen** [comment]
~~~
<el-menu-item index="3" route="{path: '/home/:id'}">
~~~

**Comment by QingWei-Li** [comment]
fixed via #17
