### ISSUE TITLE
时间选择器 DatePicker 的 disabledDate 限制范围 特定情况下倒选的时候无法自动赋值并关闭 

### ISSUE THREAD

**Issue by RedFlagRF** [ElementUI/element-starter#125]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/48118178/182759664-09ff2099-337b-4356-97fb-9f7988224b03.png">
 
# 版本信息
vue: 2.6.12,
 element-ui: 2.15.9,
 ~~~js
  data() {
    return {
      pickerOptions: {
        disabledDate:time=> {
          return time.getTime() > new Date()
        }
      },
    }
  },
~~~
# 目的

 限制结束时间不超过今天

# 注意事项
- 代码经过了精简， 完整目的就是封装一个可以选择是否限制结束时间的组件。
- 必须选择当月的范围，选择上个月的话又是正常的。

# 重现步骤
1. 先点结束时间,再点开始时间, 发现不会自动关闭时间选择框，而且值不回显。
2. 重复步骤1， 发现又正常了
3. 先刷新页面，然后点开始时间，接着点结束时间，一切正常。
4. 让`disabledDate`直接返回false,重复步骤1，2，都是一切正常。

**Comment by RedFlagRF** [comment]
我找到问题了, 这个版本有缺陷
element-ui/lib/element-ui.common.js中的isValidValue函数写得太精简，而且判断顺序错了。
# 问题原因
函数目的是交易是否有效的值，基本上就是校验：
"是否数组且开始时间和结束时间非空&&获取开始时间戳 <= 结束时间戳&&如果设置了disabledDate ，检查时间区间是否合理"。
简化一下就是： "true&&开始时间戳<=结束时间戳&&true"  
再简化就是  "开始时间戳<=true"
结果就是false
由于返回了false，不发送pick事件，导致无法正常赋值且关闭

~~~js
  handleConfirm: function handleConfirm() {
                var visible = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : false;

                if (this.isValidValue([this.minDate, this.maxDate])) {
                    this.$emit('pick', [this.minDate, this.maxDate], visible);
                }
            },
  isValidValue: function isValidValue(value) {
                return Array.isArray(value) && value && value[0] && value[1] && Object(date_util_["isDate"])(value[0]) && Object(date_util_["isDate"])(value[1]) && value[0].getTime() <= value[1].getTime() && (typeof this.disabledDate === 'function' ? !this.disabledDate(value[0]) && !this.disabledDate(value[1]) : true);
            },
~~~
<img width="477" alt="image" src="https://user-images.githubusercontent.com/48118178/182779175-3a42014b-7957-4bef-94fa-1d41ecc6825f.png">

# 解决办法
 调换一下右侧表达式的判断顺序把`value[1].getTime() `放在最后面

**Comment by chao325** [comment]
这个貌似是你代码bug。

**Comment by RedFlagRF** [comment]
我自己的问题， 对时分秒进行了格式化，导致判断错误
