### ISSUE TITLE
build后的字体文件路径不正确

### ISSUE THREAD

**Issue by lx544690189** [ElementUI/element-starter#13]
不知道是我配置问题还是什么，build后在浏览器访问，字体文件路径会是：/dest/字体文件，应该是dest/字体文件吧

**Comment by lx544690189** [comment]
在webpack.config.js里publicPath: '/dist/'改成publicPath: 'dist/'就对了

**Comment by crazy0x** [comment]
build后一些资源显示错误，也是同样的问题，已解决

**Comment by QingWei-Li** [comment]
fixed via #17
