### ISSUE TITLE
npm run

### ISSUE THREAD

**Issue by yuanyuanshen** [ElementUI/element-starter#14]
Error when rendering component <ElButton>: 报错，不知道为什么导致的呢

**Comment by yuanyuanshen** [comment]
Error when rendering component <ElButton>: 报错，不知道为什么导致的呢

**Comment by yuanyuanshen** [comment]
已解决，Vue 2.1.5 将 _h 重命名为 _c，而 Element 目前发的版本都是用以前的 compiler 编译的，导致新版 runtime 无法运行 Element。目前的解决方案是锁定 Vue 的版本为 2.1.4

锁定vue相关版本

npm remove vue #卸载相关的版本
# 重新安装一下版本
"vue-template-compiler": "2.1.4"
"vue-loader": "10.0.0"
"vue": "2.1.4"

**Comment by Abbotton** [comment]
@yuanyuanshen 非常感谢，已经解决。希望官方能尽快修复。

**Comment by ss098** [comment]
经过测试，可行有效，非常感谢。
