### ISSUE TITLE
npm run dev failure

### ISSUE THREAD

**Issue by lichinlichin** [ElementUI/element-starter#21]
![4 c4a8zxfm g fwerjeg41](https://cloud.githubusercontent.com/assets/13887816/22190962/df1f68b8-e161-11e6-9f07-bd0d200b55aa.png)

but it works well in other computer with same versions of NPM & NODE, (win7)

**Comment by mohuishou** [comment]
I encountered the same problem。
solution: delete the node_modules folder，and then `npm install`,it works well
