### ISSUE TITLE
选择器 select value为object时，label值无法正常显示

### ISSUE THREAD

**Issue by armysheng** [ElementUI/element-starter#23]
参看[这个](http://jsfiddle.net/z840rna3/1/)代码。当 select的value值是对象，不是string时，选中label值无法正常显示

**Comment by Leopoldthecoder** [comment]
确保引用的是同一个对象：http://jsfiddle.net/z840rna3/2/
另外，请在 [这里](https://github.com/ElemeFE/element) 提 issue。
