### ISSUE TITLE
怎么修改element-ui组件中的源代码

### ISSUE THREAD

**Issue by liuyufan** [ElementUI/element-starter#29]
需要改一下源码，但是不知道怎么改才会生效

**Comment by vicvinc** [comment]
同问，想修改组建中的一些功能，然后集成使用，但是打包的工具不知道怎么和webpack兼容起来用，babel的jsx transform也不起作用

**Comment by vicvinc** [comment]
能否提供一个tourial可以直接从源码引用组建，对构建工具可以提供多套的支持

**Comment by vicvinc** [comment]
@liuyufan  搞了一个简单的流程，可以看看[element-uploader-draggable](https://github.com/vicvinc/element-uploader-customer.git)，具体的功能是给upload增加了一个拖拽

**Comment by westfalenxqq** [comment]
@vicvinc 链接404了，请教一下改完源码后如何编译才能生效

**Comment by vicvinc** [comment]
@westfalenxqq 修改了一下链接地址，改了下插件，加了个裁剪和上传的拖拽排序，没仔细完善，不过大体的集成流程就这样了应该…… [希望有用](https://github.com/vicvinc/element-image-uploader)

**Comment by westfalenxqq** [comment]
@vicvinc 感谢，能不能简单的解释一下流程，我看了一下源代码没怎么看明白

**Comment by vicvinc** [comment]
@westfalenxqq 就是import 源码，然后在webpack里面alias一下element-ui到源码目录，最后用的时候直接import就行了
