### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by hagcin** [ElementUI/element-starter#42]
There is an error in the webpack config.
I was able to get around it by changing the following lines.

`module.exports = (options = {}) => ({`

to

```
const options = {}
module.exports = {

```

and 

` filename: options.dev ? '[name].js' : '[name].js?[chunkhash]',`

to

`filename: options.dev ? '[name].js' : '[name].js?[hash]',`

**The error:**

> element-starter@ dev /Users/nwinner/Documents/personal/vuejs/element-starter
> webpack-dev-server --inline --hot --env.dev

/Users/nwinner/Documents/personal/vuejs/element-starter/webpack.config.js:7
module.exports = (options = {}) => ({
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/Users/nwinner/Documents/personal/vuejs/element-starter/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/nwinner/Documents/personal/vuejs/element-starter/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-starter@ dev: `webpack-dev-server --inline --hot --env.dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the element-starter@ dev script 'webpack-dev-server --inline --hot --env.dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the element-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --env.dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs element-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls element-starter
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nwinner/.npm/_logs/2017-05-04T19_48_35_360Z-debug.log

**The log file from error:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@4.5.0
3 info using node@v5.4.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle element-starter@~predev: element-starter@
6 silly lifecycle element-starter@~predev: no script for predev, continuing
7 info lifecycle element-starter@~dev: element-starter@
8 verbose lifecycle element-starter@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle element-starter@~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/nwinner/Documents/personal/vuejs/element-starter/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle element-starter@~dev: CWD: /Users/nwinner/Documents/personal/vuejs/element-starter
11 silly lifecycle element-starter@~dev: Args: [ '-c', 'webpack-dev-server --inline --hot --env.dev' ]
12 silly lifecycle element-starter@~dev: Returned: code: 1  signal: null
13 info lifecycle element-starter@~dev: Failed to exec dev script
14 verbose stack Error: element-starter@ dev: `webpack-dev-server --inline --hot --env.dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid element-starter@
16 verbose cwd /Users/nwinner/Documents/personal/vuejs/element-starter
17 verbose Darwin 16.4.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 verbose node v5.4.1
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error element-starter@ dev: `webpack-dev-server --inline --hot --env.dev`
23 error Exit status 1
24 error Failed at the element-starter@ dev script 'webpack-dev-server --inline --hot --env.dev'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the element-starter package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack-dev-server --inline --hot --env.dev
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs element-starter
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls element-starter
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by QingWei-Li** [comment]
Environment

Node >= 6
