### ISSUE TITLE
new one project webpack.config.js options the default value  report an error

### ISSUE THREAD

**Issue by qwe5788319** [ElementUI/element-starter#45]
[error view](http://chuantu.biz/t5/93/1495718679x2890173741.png) the default value  remove is ok

**Comment by qwe5788319** [comment]
[](http://chuantu.biz/t5/93/1495716007x2890173741.png)

**Comment by foreverwing99** [comment]
hello,I am sorry, I don't know where is  the default value,which one should be removed.And I have remove the node_modules ,but it doesn't work!

**Comment by QingWei-Li** [comment]
https://github.com/ElementUI/element-starter/blob/master/package.json#L14-L16
