### ISSUE TITLE
Yarn not install

### ISSUE THREAD

**Issue by bravist** [ElementUI/element-starter#51]
Using `yarn` can not install dependency when clone this repository.   

but, using `cnpm install` or `npm install` it worked

**Comment by SherlockStd** [comment]
do you have an error to provide ?

**Comment by snachx** [comment]
Maybe it's just because you forget to install yarn before running it.

**Comment by SherlockStd** [comment]
@snachx that would be very funny, but I think he's used to Yarn so it should be installed, kinda errors everybody can understand anyway ^^

@Leopoldthecoder I think you can close this issue, the opener didn't responded since 2 months :smile:
