### ISSUE TITLE
编译时报 vue@2.5.16 和 vue-template-compiler@2.5.2 版本不符异常

### ISSUE THREAD

**Issue by tuzkimo** [ElementUI/element-starter#67]
查看 https://registry.yarnpkg.com/vue-template-compiler/ 发现最新版本为 `2.5.16`，
手动将 `package.json` 的 `vue-template-compiler` 版本改为 `2.5.16`，
`yarn.lock`  的 `vue-template-compiler` 版本改为 `2.5.16`，地址改为 `https://registry.npmjs.org/vue-template-compiler/-/vue-template-compiler-2.5.16.tgz#93b48570e56c720cdf3f051cc15287c26fbd04cb`，
重新 `yarn` 一次，然后 `npm run dev` 编译运行成功。

请问可以这样解决吗？谢谢。

**Comment by Leopoldthecoder** [comment]
已修复。
