### ISSUE TITLE
安装完依赖以后报错了，npm run dev 启动不了项目。。。

### ISSUE THREAD

**Issue by xuelanghp** [ElementUI/element-starter#69]
![qq 20180417115413](https://user-images.githubusercontent.com/18714299/38847822-2e0e5ed0-4236-11e8-909f-727ee3a0593b.png)
![qq 20180417115434](https://user-images.githubusercontent.com/18714299/38847824-2e5fb32a-4236-11e8-92a7-6f51b0943e91.png)
问一下，是什么原因呢？

**Comment by Leopoldthecoder** [comment]
你的 8010 端口被占用了。

**Comment by xuelanghp** [comment]
ok，node.exe占用了8010，另外需要update vue-template-compiler；
解决 了。。。
