### ISSUE TITLE
webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by chenxingyu-cs** [ElementUI/element-starter#7]
![screen shot 2016-11-14 at 4 25 11 pm](https://cloud.githubusercontent.com/assets/6926994/20288272/fe9dad6a-aa86-11e6-8f4a-b9c0ff038dbc.png)

按照你写的命令，最后一步出了这样的错，不知道怎么解决。。。

**Comment by QingWei-Li** [comment]
估计 webpack 又来 breaking change 了，我今天把这份配置改成 webpack 2 的吧

**Comment by baibotao** [comment]
![1242](https://cloud.githubusercontent.com/assets/8530078/20297534/f0f7df4e-ab4b-11e6-80de-ade4162a6cf1.PNG)
我在windows上按照readmin的步骤安装完毕后，执行npm run dev,也出现通用的错误，希望能得到帮助，谢谢！
