### ISSUE TITLE
可以使用 webpack4 吗？

### ISSUE THREAD

**Issue by ChillingVan** [ElementUI/element-starter#70]
目前本项目是用webpack2.4.1的，我尝试使用webpack4.8.3就直接报错了：

> webpack-dev-server --inline --hot --env.dev
> 
> module.js:538
>     throw err;
>     ^
> 
> Error: Cannot find module 'webpack/bin/config-yargs'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (D:\develop-win\javascript\opensource\element-starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js:54:1)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! element-starter@ dev: `webpack-dev-server --inline --hot --env.dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the element-starter@ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:

**Comment by ghost** [comment]
我把所有依赖更新到最新版,然后稍微修改下就起来了.

**Comment by ChillingVan** [comment]
谢谢，之前新手，不太懂webpack的规则，不知道版本要互相匹配。 坑真多。。
