### ISSUE TITLE
steps IE10失效

### ISSUE THREAD

**Issue by wangshanbo** [ElementUI/element-starter#72]
http://element-cn.eleme.io/#/zh-CN/component/steps
 el-steps类下面的所有el-step类回添加行间样式flex-basis，但是IE10并不支持

**Comment by erDuo10** [comment]
> http://element-cn.eleme.io/#/zh-CN/component/steps
> el-steps类下面的所有el-step类回添加行间样式flex-basis，但是IE10并不支持

您这个问题解决了吗，我现在也遇到了这个问题，ie11正常显示，ie10,ie9均不能正常显示

**Comment by DeveilMayCry** [comment]
> 
> 
> > http://element-cn.eleme.io/#/zh-CN/component/steps
> > el-steps类下面的所有el-step类回添加行间样式flex-basis，但是IE10并不支持
> 
> 您这个问题解决了吗，我现在也遇到了这个问题，ie11正常显示，ie10,ie9均不能正常显示

您好，您解决了吗，我也遇到了。

**Comment by liuzm7188** [comment]
为啥关闭了呢，怎么解决呢
