### ISSUE TITLE
配置vue-cli3时,  字体加载问题

### ISSUE THREAD

**Issue by cifaz** [ElementUI/element-starter#77]
使用vue-cli3搭建环境, 使用默认css-loader加载时, 
在main.js中加入import 'element-ui/lib/theme-chalk/index.css';  会报字体路径不对, 经查看, 如下代码
@font-face{font-family:element-icons;src:url(fonts/element-icons.woff)
此类路径应该改为
@font-face{font-family:element-icons;src:url(./fonts/element-icons.woff)

测试过vue-cli及@vue/cli不会报错
自定义的vue也不会报错, 使用vue版本2.5.2

**Comment by cifaz** [comment]
错误:
ERROR in ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./node_modules/element-ui/lib/theme-chalk
/index.css)
Module not found: Error: Can't resolve 'fonts/element-icons.ttf' in 'E:\project\nodejs\webstorm\201808\testaaa\node_modules\element-ui\lib\theme-chalk'
 @ ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./node_modules/element-ui/lib/theme-chalk/index
.css) 7:781-815
 @ ./node_modules/element-ui/lib/theme-chalk/index.css
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.186:80/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

ERROR in ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./node_modules/element-ui/lib/theme-chalk
/index.css)
Module not found: Error: Can't resolve 'fonts/element-icons.woff' in 'E:\project\nodejs\webstorm\201808\testaaa\node_modules\element-ui\lib\theme-chalk'
 @ ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./node_modules/element-ui/lib/theme-chalk/index
.css) 7:707-742
 @ ./node_modules/element-ui/lib/theme-chalk/index.css
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.186:80/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by MichealYang1001** [comment]
我也遇到了这个问题，vue的版本是3.0.1。请问这个问题怎么解决的

**Comment by cifaz** [comment]
vue-cli3, 暂时不要配置cssloader中的module为true即可, 他会把所有的认为是模块, 会出问题

**Comment by JamesZFS** [comment]
大概同上，在修改config/index.js的`build.assetsPublicPath = './',` 时，我也出现了 fonts not found 的问题
